### ISSUE TITLE
Missing file detect_face.py

### ISSUE THREAD

**Issue by TadeasFrycak** [IS2AI/TFW#3]
Hello, 

I would really like to use your `Face` models, but I cannot find the `detect_face.py` file mentioned in README, would you please share it with me?

Thank you for your work!

**Comment by akuzdeuov** [comment]
Hello, 

Thank you for your interest in our project. The ```detect_face.py``` file is located in the original [YOLO5Face repo](https://github.com/deepcam-cn/yolov5-face/blob/master/detect_face.py ): 
First, you need to download [YOLOv5](https://github.com/ultralytics/yolov5) repo and install the required packages: 
```
$ git clone https://github.com/ultralytics/yolov5 
$ cd yolov5
$ pip install -r requirements.txt  
```
Then, download the YOLO5Face repo:
```
$ git clone https://github.com/deepcam-cn/yolov5-face.git
$ cd yolov5-face
```
To use our pre-trained face models, download this file from [Google Drive](https://drive.google.com/drive/folders/12ub57wP1hZ4tL2WH7TrUpmbvXXIdi3NU) and unzip it in the ```yolo5-face/weights ``` directory. Then, run the following script:
```
$ python detect_face.py --weights PATH_TO_MODEL --source PATH_TO_IMAGE
```

**Comment by TadeasFrycak** [comment]
It works grandly, thank you very much!
